stages:
  load_data:
    cmd: python data_processing.py load_data data/bike_sharing.csv
    deps:
      - data_processing.py
      - data/bike_sharing.csv
    outs:
      - data/raw_data.csv

  preprocess_data:
    cmd: python data_processing.py preprocess_data
    deps:
      - data_processing.py
      - data/raw_data.csv
    outs:
      - data/X_train.csv
      - data/X_test.csv
      - data/y_train.csv
      - data/y_test.csv

  train_pipeline:
    cmd: python model_training.py train_pipeline
    deps:
      - model_training.py
      - data/X_train.csv
      - data/y_train.csv
    outs:
      - models/pipeline.pkl

  evaluate_pipeline:
    cmd: python model_training.py evaluate_pipeline
    deps:
      - model_training.py
      - models/pipeline.pkl
      - data/X_test.csv
      - data/y_test.csv
    outs:
      - metrics.json
